### PR TITLE
Migrate to Unity.Container 5.0.0

### PR DESCRIPTION
**Pull request by antoshkab**
Update Unity to version 5.0 and CommonServiceLocator to version to 2.0.1.

### CODE REVIEW

**Comment by viceice** [comment]
Is the `CommonServiceLocator` reference still required? Can we remove that? Because `Unity` has no longer a reference on that.

**Review by viceice — CHANGES_REQUESTED** [review]
Please remove `CommonServiceLocator` because it seems that this is no longer a dependency.

**Comment by viceice** [comment]
Maybe we should switch to the new `Unity.Container` package?

**Comment by antoshkab** [comment]
Didn't see about CommonServiceLocator in release, sorry  :)
Removed CommonServiceLocator and changed Unity to Unity.Container

**Review by viceice — APPROVED** [review]
Looks good 👍

**Comment by antoshkab** [comment]
thx :)

**Comment by viceice** [comment]
Added a [prerelease](https://www.nuget.org/packages/Unity.Wcf/4.0.0-rc02) to nuget

**Pull request merged**
